
all:
	$(MAKE) -C src
.PHONY: all

stage:
	$(MAKE) -C src stage
.PHONY: stage

install:
	$(MAKE) -C src install
.PHONY: install

# src/Makefile's clean also cleans the stage directories
clean:
	$(MAKE) -C src clean



.PHONY: clean


