.TH AN-PNMTOFITS "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
an\-pnmtofits \- Convert PNM file to FITS.
.SH SYNOPSIS
.B
an\-pnmtofits
[options] [\fIinput-file\fR [\fIoutput-file\fR]]
.SH DESCRIPTION
Convert a PNM file to a FITS file. If no input file is given, stdin is used.
If no output file is given, stdout is used.
.TP
\fB\-o\fR \fIfile\fR
Output file (default stdout)
.TP
\fB\-v\fR
Verbose mode
.TP
\fB\-q\fR
Quiet mode
.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
