.TH FITS-FLIP-ENDIAN "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
fits-flip-endian \- Endian swapping of FITS binary tables.
.SH SYNOPSIS
.B
fits\-flip\-endian
\fB\-i\fR \fIinput-file\fR
\fB\-o\fR \fIoutput-file\fR
[ \fB\-e\fR \fIext\fR \fB\-s\fR \fIsize\fR ] ...
.SH OPTIONS
.TP
\fB\-i\fR \fIfile\fR
Input file
.TP
\fB\-o\fR \fIfile\fR
Output file
.TP
\fB\-e\fR \fIext\fR
Extension number
.TP
\fB\-s\fR \fIsize\fR
Data size in bytes
.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
