.TH FITS-GUESS-SCALE "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
fits-guess-scale \- Try to guess the scale of an image based on FITS headers.
.SH SYNOPSIS
.B
fits\-guess\-scale
\fIFITS-file\fR
.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
