.TH GET-WCS "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
get\-wcs \- Try to interpret an existing WCS header.
.SH SYNOPSIS
.B
get\-wcs
[options]
\fIinput-file\fR
.SH OPTIONS
.TP
\fB\-e\fR \fIext\fR
Extension number
.TP
\fB\-o\fR \fIfile\fR
Output file
.TP
\fB\-t\fR
Force TAN (not SIP)
.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
