.TH PLOTSTUFF "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
plotstuff \- Undocumented program of astrometric.net
.SH SYNOPSIS
.B plotstuff
[\fI\,options\/\fR] \fI\,> output.png\/\fR
.SH OPTIONS
.TP
\fB\-o\fR \fIfile\fR
Output file (default: stdout)
.TP
\fB\-P\fR
Write PPM output instead of PNG.
.TP
\fB\-j\fR
Write JPEG output.
.TP
\fB\-J\fR
Write PDF output.
.TP
\fB\-W\fR \fIwidth\fR
Width of output image (default: data\-dependent).
.TP
\fB\-H\fIheight\fR
Height of output image (default: data\-dependent).
.TP
\fB\-v\fR
+verbose
.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
