.TH SEARCH-INDEX "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
search-index \- Undocumented program of astrometry.net
.SH SYNOPSIS
.B search-index
[\fIoptions\fR] \fIindex-files\fR
.SH OPTIONS
.TP
\fB\-r\fR \fIra\fR
RA (deg)
.TP
\fB\-d\fR \fIdec\fR
DEC (deg)
.TP
\fB\-R\fR \fIradius\fR
Radius(deg)
.TP
\fB\-o \fIfile\fR
Save results in FITS table; tag\-along columns must be the same in all indices
.TP
\fB\-v\fR
+verbose
.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
