.TH SUBTABLE "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
subtable \- Pull out a set of columns from a many-column FITS binary table.
.SH SYNOPSIS
.B
subtable
\fB\-i\fR \fIinput-file\fR \fB\-o\fR \fIoutput-file\fR
\fB\-c\fR \fIcol-name\fR [\fB\-c\fR \fIcol-name\fR ...]
.SH OPTIONS
.TP
\fB\-i\fR \fIfile\fR
Input file
.TP
\fB\-o\fR \fIfile\fR
Output file
.TP
\fB\-c\fR \fIname\fR
Column name
.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
