.TH TABSORT "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
tabsort \- Sort a FITS binary table based on values in one column.
.SH SYNOPSIS
.B
tabsort
[options] \fIcolumn-name\fR \fIinput-file\fR \fIoutput-file\fR
.SH OPTIONS
.TP
\fB\-d\fR
Sort in descending order (default: ascending)
.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
