.TH WCS-GRAB "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
wcs-grab \- Try to interpret an existing WCS header.
.SH SYNOPSIS
.B wcs-grab
\fIinput-filename extension output-filename\fR

.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
