.TH WCS-MATCH "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
wcs-match \- Prints x and y coordinates of invariant point
.SH SYNOPSIS
.B wcs-match
.SH DESCRIPTION
.TP
\fB\-1\fR \fIfile\fR
WCS first input file
.TP
\fB\-2\fR \fIfile\fR
WCS second input file
.TP
\fB\-h\fR
.TP
\fB\-v\fR
+verbose

.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
