.TH WCSINFO "1" "July 2015" "0.56" "astrometry.net"
.SH NAME
wcsinfo \- print simple properties of WCS headers (scale, rotation, etc)
.SH SYNOPSIS
.B wcsinfo
[options]
\fIwcs-file\fR
.SH OPTIONS
.TP
\fB\-e\fR \fIextension\fR
Read from given HDU (default 0 = primary)
.TP
\fB\-W\fR \fIwidth\fR
Set/override IMAGEW
.TP
\fB\-H\fR \fIheight\fR
Set/override IMAGEH
.SH AUTHOR
The Astrometry.net team. Principal investigators are David W. Hogg (NYU) and
Dustin Lang (CMU).
.SH SEE ALSO
http://astrometry.net
