application: astrometry-render
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/
  static_dir: static

- url: /tile.*
  script: julia.py

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: hello.py

