# This file is part of the Astrometry.net suite.
# Licensed under a 3-clause BSD style license - see LICENSE

ZLIB_INC ?= $(shell pkg-config --cflags zlib 2>/dev/null)
ZLIB_LIB ?= $(shell pkg-config --libs zlib 2>/dev/null || echo "-lz")
