# This file is part of the Astrometry.net suite.
# Licensed under a 3-clause BSD style license - see LICENSE

PNG_INC ?= $(shell pkg-config --cflags libpng 2>/dev/null)
PNG_LIB ?= $(shell pkg-config --libs libpng 2>/dev/null)
