# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-22 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0004_auto_20201112_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='job_finished',
            field=models.BooleanField(default=False),
        ),
    ]
