# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-22 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0005_userimage_job_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='job_finished',
            new_name='has_job',
        ),
    ]
