# Generated by Django 4.0.1 on 2025-01-31 16:21

# (and hand edited to remove unwanted extras)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0006_auto_20210522_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='n_objs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
