#! /bin/bash

# How to pre-render raw (floating-point) images:
Z=5;
N=`echo "2^$Z" | bc -l`;
for ((I=0; I<N; I++)); do
    for ((J=0; J<N; J++)); do
        x1=`echo "$I/$N" | bc -l`;
        x2=`echo "($I+1)/$N" | bc -l`;
        y1=`echo "$J/$N" | bc -l`;
        y2=`echo "($J+1)/$N" | bc -l`;
        out=`printf usnob_z%i_%02i_%02i.raw $Z $I $J`;
        log=`printf log-$Z-%02i-%02i $I $J`;
        ~/test/tilecache/render/tilerender -p -R -M -l 'usnob' -x $x1 -X $x2 -y $y1 -Y $y2 -w 256 -h 256 > $out 2> $log
    done
done


# how i did the first few ones by hand
#tilerender -x -180.000000 -y 0.000000 -X 0.000000 -Y 85.051129 -w 256 -h 256 -l 'usnob' -R > usnob_z1_00_00.raw 2> log-1-00-00
#tilerender -x 0.000000 -y 0.000000 -X 180.000000 -Y 85.051129 -w 256 -h 256 -l 'usnob' -R > usnob_z1_00_01.raw 2> log-1-00-01
#tilerender -x -180.000000 -X 0.000000 -y -85.051129 -Y 0 -w 256 -h 256 -l 'usnob' -R > usnob_z1_01_00.raw 2> log-1-01-00
#tilerender -x 0.000000 -X 180.000000 -y -85.051129 -Y 0 -w 256 -h 256 -l 'usnob' -R > usnob_z1_01_01.raw 2> log-1-01-01

