#! /bin/bash

#. /data1/dstn/dsolver/astrometry/net/ice/ice-config-hydra

echo "Applications:"
echo "application list" | ./startadmin | grep -v "Ice 3.3"

echo
echo "Nodes:"
nodes=$(echo "node list" | ./startadmin | grep "neuron")
echo $nodes

for x in $nodes; do
	echo "Node $x:"
	echo "node ping $x" | ./startadmin | grep -v "Ice 3.3"
done

