#! /bin/bash

. /data1/dstn/dsolver/astrometry/net/ice/ice-config-hydra

icegridadmin --Ice.Config=config.grid <<END
application remove Solver
application add solver.xml
application list
node list
server list
END
echo

#application update solver.xml
