#! /bin/bash

set -e
# This script gets run on astro.cs.toronto.edu via ssh from oven.

# Careful about writing things to stdout - we pipe it to tar on the other end.

# Assume that we start in the directory containing the "blind" executable.
PWD=`pwd`
BLIND="$PWD/blind"

# Read jobid
read -s jobid

# Replace "-" by "/" in the jobid.
jobid=`echo "$jobid" | sed s+-+/+g`

# Create our job directory.
cd /tmp
mkdir -p $jobid
cd $jobid
tar xf -

# Index path replacement.
sed s+/home/gmaps/ontheweb-indexes+/data1/INDEXES+ < input > input.c27

# stderr goes back over the ssh tunnel to the log file on oven.
$BLIND < input.c27 > blind.stdout

# Send back all the files we generated!
tar cf - *
