#! /bin/bash

. /data1/dstn/dsolver/astrometry/net/ice/ice-config-hydra

NODEDIR=db/node-registry
mkdir -p ${NODEDIR}

PIDFILE=/tmp/iceregistry.pid

KILLPID=$(cat ${PIDFILE})
echo "Killing old registry pid ${KILLPID}"
kill ${KILLPID}

icegridregistry \
    --Ice.Config=config.grid \
    --IceGrid.Node.Name=registry \
    --IceGrid.Node.Data=${NODEDIR} \
    --daemon --nochdir --pidfile ${PIDFILE} \
    < /dev/null >> ${LOG}/registry.log 2>&1

