#! /bin/bash

. /data1/dstn/dsolver/astrometry/net/ice/ice-config-hydra

NODEDIR=db/node-registry
mkdir -p ${NODEDIR}

icegridregistry \
    --Ice.Config=config.grid \
    --IceGrid.Node.Name=registry \
    --IceGrid.Node.Data=${NODEDIR} \
    < /dev/null >> ${LOG}/registry.log 2>&1

