#! /bin/bash

# called via ssh from gmaps@oven.

. /data1/dstn/dsolver/astrometry/net/ice/ice-config-hydra

#killall sessionserver icegridregistry glacier2router >> ${LOG}/glacier2.log 2>&1
killall icegridregistry glacier2router >> ${LOG}/glacier2.log 2>&1

#./sessionserver < /dev/null >> ${LOG}/sessionserver.log 2>&1 &
#sleep 1

glacier2router --Ice.Config=config.glacier2 < /dev/null >> ${LOG}/glacier2.log 2>&1 &
sleep 1
. startreg

wait
