#! /bin/bash

# cluster-fork --bg --nodes neuron-0-%d:0-23 /data1/dstn/dsolver/astrometry/net/ice/startdaemon
## TEMP  -- avoid nodes 12-15 (until Mar 11/2009)


# TEST
cluster-fork --bg --nodes neuron-0-%d:0-4  /data1/dstn/dsolver/astrometry/net/ice/startdaemon

#cluster-fork --bg --nodes neuron-0-%d:0-11  /data1/dstn/dsolver/astrometry/net/ice/startdaemon
#cluster-fork --bg --nodes neuron-0-%d:16-24 /data1/dstn/dsolver/astrometry/net/ice/startdaemon

exit 0

