#! /bin/bash

. /data1/dstn/dsolver/astrometry/net/ice/ice-config-hydra

NODEDIR=db/node-`hostname -s`
mkdir -p ${NODEDIR}

echo "killing existing icegridnode..."
. stopdaemon
echo "starting icegridnode..."
icegridnode --Ice.Config=config.grid \
    --IceGrid.Node.Name=`hostname -s` \
    --IceGrid.Node.Data=${NODEDIR} \
    --deploy solver.xml \
    --checkdb \
    --daemon --nochdir --noclose \
    --pidfile ${PIDS}/icegridnode-`hostname -s`.pid \
    < /dev/null \
    >> ${LOG}/server-`hostname -s`.log \
    2>&1
echo "started icegridnode."
