#! /bin/bash

. /data1/dstn/dsolver/astrometry/net/ice/ice-config-hydra

# graceful...
PIDFILE=${PIDS}/icegridnode-`hostname -s`.pid
if [ -r $PIDFILE ]; then
    KILLPID=`cat ${PIDFILE}`
    echo "Killing pid ${KILLPID}..."
    kill ${KILLPID}
fi
sleep 1
# ... or not
killall icegridnode python

