.TH frameq 1 "21 Nov 2002"
.SH NAME 
frameq \- Classify frames from a directory
.SH SYNOPSIS
.B frameq 
<directory_name>
.SH DESCRIPTION
.PP
.B frameq
is aimed at classifying lists of frames a bit like the DO and RBS do. The
aim is to put frames produced by the same template execution together.
.PP
.SH ALGORITHM
The classification is using the TPl.NEXP and TPL.EXPNO to identify the
sequences of frames. The TPL.ID keyword is also used.
.SH OPTIONS
None
.SH FILES
.PP
Files shall all comply with FITS format and contain keyword like TPL keys.
